Refining the dialyzer configuration
Byzanteam/jet_cli pull request #13
Opened 2023-02-22 09:21 UTC by joeywang321

根据阅读库和测试所得，如果 priv/plts 目录下没有 *.plt 文件被缓存，那么在使用 actions/cache 进行缓存时，该目录下的任何内容都不会被缓存下来，所以我并没有在`.gitignore`文件中添加git不跟踪缓存的信息，我修改了模版文件和本库的elixir.yml文件，添加了判断，判断缓存是否存在，如果缓存存在我们就直接根据缓存执行，如果不存在我们就先创建缓存然后执行，这样可以减少时间。这样我们使用cli生成的每一个actions都会自动判断有没有dialyzer的缓存，然后在执行代码分析。如果在`.gitignore`文件中忽略了缓存不上传的话。那么其实就没有在模版文件中添加读取缓存这一步，因为一定会读取失败，就直接执行github的分析是最好的。
总结：添加一个判断缓存是否存在，不存在创建，存在就读取。提升了生成ci的健壮性，不会出现没有缓存上传出现读取失败的情况

2023-02-22 09:36 UTC, fahchen commented
上面的理解有问题，.gitignore 忽略的文件不会加入版本管理，但每次 mix dialyzer 的时候会生成的，本地就直接用自己的本地缓存，CI 用 action cache。
你这个 PR 是解决 #9 这个 issue 吗？

2023-02-22 09:54 UTC, joeywang321 commented
> 上面的理解有问题，.gitignore 忽略的文件不会加入版本管理，但每次 mix dialyzer 的时候会生成的，本地就直接用自己的本地缓存，CI 用 action cache。 你这个 PR 是解决 #9 这个 issue 吗？

可是如果我加入.gitignore 里面，我提pr的时候运行会报错，提示找不到缓存文件

2023-02-22 10:07 UTC, fahchen commented
你按 #9 的描述来实现

2023-02-23 02:49 UTC, joeywang321 commented
> 你按 #9 的描述来实现

@fahchen sf,请求检阅

2023-02-23 02:57 UTC, fahchen requested changes
分成两个改动：
1. 针对模版的改动
2. 针对当前这个 repo 的改动

2023-02-23 02:58 UTC, fahchen commented on .github/workflows/elixir.yml
> +
针对当前 repo 的改动把这个去掉就可以了

2023-02-23 07:56 UTC, fahchen commented
针对模版的改动按照 #9 来做

2023-02-23 10:26 UTC, merged